apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auto-nexus

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: nexus

  ports:
    - name: http
      port: 80
      nodePort: 30081

  type: NodePort
